"use strict";
const _topic1 = "const nums = [1, 2, 3];\nconsole.log(nums[0], nums.at(-1));";
document.querySelector("#topic1Code code").textContent = _topic1;
const _topic2 = "const cart = [\"bread\"];\ncart.push(\"milk\");\ncart.unshift(\"rice\");\nconst last = cart.pop();\nconsole.log(cart, last);";
document.querySelector("#topic2Code code").textContent = _topic2;
const _topic3 = "const arr = [10, 20, 30];\nfor (const v of arr) console.log(v);\narr.forEach((v, i) => console.log(i, v));";
document.querySelector("#topic3Code code").textContent = _topic3;
const _topic4 = "const scores = [40, 82, 55];\nconst passers = scores.filter((s) => s >= 60);\nconst curved = scores.map((s) => s + 5);\nconst sum = scores.reduce((a, b) => a + b, 0);\nconsole.log(passers, curved, sum);";
document.querySelector("#topic4Code code").textContent = _topic4;
const _topic5 = "const ids = [2, 4, 6];\nconsole.log(ids.find((x) => x > 3));\nconsole.log(ids.some((x) => x % 2 === 1));\nconsole.log(ids.every((x) => x % 2 === 0));";
document.querySelector("#topic5Code code").textContent = _topic5;
const _topic6 = "const a = [1, 2];\nconst b = [3, ...a];\nconsole.log(b);";
document.querySelector("#topic6Code code").textContent = _topic6;
