"use strict";
const _topic1 = "const marks = 72;\nif (marks >= 90) console.log(\"A\");\nelse if (marks >= 75) console.log(\"B\");\nelse if (marks >= 60) console.log(\"C\");\nelse console.log(\"F\");";
document.querySelector("#topic1Code code").textContent = _topic1;
const _topic2 = "const day = \"Wednesday\";\nswitch (day) {\n  case \"Monday\":\n  case \"Tuesday\":\n  case \"Wednesday\":\n  case \"Thursday\":\n  case \"Friday\":\n    console.log(\"Weekday\");\n    break;\n  case \"Saturday\":\n  case \"Sunday\":\n    console.log(\"Weekend\");\n    break;\n  default:\n    console.log(\"Invalid day\");\n}";
document.querySelector("#topic2Code code").textContent = _topic2;
const _topic3 = "const values = [0, \"0\", \"\", \" \", null, undefined, NaN, [], {}, \"false\"];\nvalues.forEach((v) => {\n  if (v) console.log(JSON.stringify(v), \"truthy\");\n  else console.log(JSON.stringify(v), \"falsy\");\n});";
document.querySelector("#topic3Code code").textContent = _topic3;
const _topic4 = "function check(user) {\n  if (!user) return;\n  if (!user.isActive) return;\n  if (user.age < 18) return;\n  console.log(\"Access granted\");\n}";
document.querySelector("#topic4Code code").textContent = _topic4;
const _topic5 = "const score = 40;\nconst label = score >= 50 ? \"pass\" : \"fail\";\nconsole.log(label);";
document.querySelector("#topic5Code code").textContent = _topic5;
const _topic6 = "// Many branches -> if/else if or switch\n// Many returns from nesting -> guard clauses";
document.querySelector("#topic6Code code").textContent = _topic6;
