"use strict";
const _topic1 = "btn.addEventListener(\"click\", () => {\n  console.log(\"clicked\");\n});";
document.querySelector("#topic1Code code").textContent = _topic1;
const _topic2 = "input.addEventListener(\"input\", (e) => {\n  console.log(e.target.value);\n});";
document.querySelector("#topic2Code code").textContent = _topic2;
const _topic3 = "form.addEventListener(\"submit\", (e) => {\n  e.preventDefault();\n});";
document.querySelector("#topic3Code code").textContent = _topic3;
const _topic4 = "list.addEventListener(\"click\", (e) => {\n  const li = e.target.closest(\"li\");\n  if (!li) return;\n  li.classList.toggle(\"done\");\n});";
document.querySelector("#topic4Code code").textContent = _topic4;
const _topic5 = "// Delegation: one listener on parent for many children";
document.querySelector("#topic5Code code").textContent = _topic5;
const _topic6 = "// mouseenter, keydown, change, focus, blur \u2014 pick per UX need";
document.querySelector("#topic6Code code").textContent = _topic6;
