"use strict";
const _topic1 = "try {\n  JSON.parse(\"{\");\n} catch (e) {\n  console.log(\"caught\", e.name);\n} finally {\n  console.log(\"always\");\n}";
document.querySelector("#topic1Code code").textContent = _topic1;
const _topic2 = "function mustPositive(n) {\n  if (n <= 0) throw new Error(\"n must be positive\");\n  return n;\n}";
document.querySelector("#topic2Code code").textContent = _topic2;
const _topic3 = "class ValidationError extends Error {\n  constructor(msg) {\n    super(msg);\n    this.name = \"ValidationError\";\n  }\n}";
document.querySelector("#topic3Code code").textContent = _topic3;
const _topic4 = "// Syntax errors and many async errors need other tools";
document.querySelector("#topic4Code code").textContent = _topic4;
const _topic5 = "// mathUtils.js\nexport const PI = 3.14;\nexport function add(a, b) {\n  return a + b;\n}\n// app.js\n// import { PI, add } from \"./mathUtils.js\";";
document.querySelector("#topic5Code code").textContent = _topic5;
const _topic6 = "export default function formatPrice(n) {\n  return \"\u20b9\" + n;\n}";
document.querySelector("#topic6Code code").textContent = _topic6;
