"use strict";
const _topic1 = "const name = \"Priya\";\nconst user = { name, age: 24 };\nconsole.log(user);";
document.querySelector("#topic1Code code").textContent = _topic1;
const _topic2 = "const u = { \"fav color\": \"blue\" };\nconsole.log(u.name, u[\"fav color\"]);";
document.querySelector("#topic2Code code").textContent = _topic2;
const _topic3 = "const acc = {\n  balance: 100,\n  deposit(n) {\n    this.balance += n;\n    return this.balance;\n  },\n};\nconsole.log(acc.deposit(50));";
document.querySelector("#topic3Code code").textContent = _topic3;
const _topic4 = "const p = { id: 1, title: \"Pen\", price: 10 };\nconst { title, price } = p;\nconsole.log(title, price);";
document.querySelector("#topic4Code code").textContent = _topic4;
const _topic5 = "const a = { x: 1 };\nconst b = { y: 2, ...a };\nconsole.log(b);";
document.querySelector("#topic5Code code").textContent = _topic5;
const _topic6 = "const o = { a: 1, b: 2 };\nconsole.log(Object.keys(o));\nconsole.log(Object.values(o));";
document.querySelector("#topic6Code code").textContent = _topic6;
