"use strict";
const _topic1 = "console.log(10 + 3, 10 - 3, 10 * 3, 10 / 3, 10 % 3, 2 ** 8);\nlet x = 5;\nx += 2; // 7";
document.querySelector("#topic1Code code").textContent = _topic1;
const _topic2 = "let score = 10;\nscore += 5;\nscore -= 3;\nscore *= 2;\nscore /= 4;\nconsole.log(score);";
document.querySelector("#topic2Code code").textContent = _topic2;
const _topic3 = "console.log(5 == \"5\", 5 === \"5\");\nconsole.log(0 == false, 0 === false);\nconsole.log(null == undefined, null === undefined);";
document.querySelector("#topic3Code code").textContent = _topic3;
const _topic4 = "console.log(true && false);\nconsole.log(true || false);\nconsole.log(!true);";
document.querySelector("#topic4Code code").textContent = _topic4;
const _topic5 = "const age = 17;\nconst mood = age >= 18 ? \"adult\" : \"minor\";\nlet username = null;\nconst display = username ?? \"Guest\";\nconst display2 = username || \"Guest\";\nconsole.log(mood, display, display2);";
document.querySelector("#topic5Code code").textContent = _topic5;
const _topic6 = "const user = { address: { city: \"Jaipur\" } };\nconsole.log(user.address?.city);\nconsole.log(user.profile?.bio); // undefined, no throw";
document.querySelector("#topic6Code code").textContent = _topic6;
