"use strict";
const _topic1 = "const el = document.querySelector(\"#app\");\nconsole.log(el);";
document.querySelector("#topic1Code code").textContent = _topic1;
const _topic2 = "const title = document.querySelector(\"h1\");\ntitle.textContent = \"Hello\";\ntitle.style.color = \"crimson\";";
document.querySelector("#topic2Code code").textContent = _topic2;
const _topic3 = "const box = document.querySelector(\".box\");\nbox.classList.add(\"active\");\nbox.classList.toggle(\"dark\");";
document.querySelector("#topic3Code code").textContent = _topic3;
const _topic4 = "const li = document.createElement(\"li\");\nli.textContent = \"New\";\ndocument.querySelector(\"ul\").appendChild(li);";
document.querySelector("#topic4Code code").textContent = _topic4;
const _topic5 = "parent.removeChild(child);\nlist.innerHTML = \"\";";
document.querySelector("#topic5Code code").textContent = _topic5;
const _topic6 = "// Prefer textContent for plain text to avoid XSS with innerHTML";
document.querySelector("#topic6Code code").textContent = _topic6;
